### ISSUE TITLE
Level 4: Implement RAG so the chatbot responds based on a given knowledge base

### ISSUE THREAD

**Issue by TinglyTingly** [TinglyTingly/Headstarter-Project-3#23]

**Comment by winstondmasi** [comment]
RAG involves:

1. Storing a knowledge base (usually as text documents)
2. Retrieving relevant information from this base when a query is received
3. Augmenting the AI's prompt using the retrieved retrieved information, if there is none continue on as normal

Note:
Since i don't want to use more api keys than necessary, i'm doing the embeddings with the HuggingFaceTransformersEmbeddings from LangChain, which uses a local model. 

(read up more about it here if interested: https://js.langchain.com/v0.2/docs/integrations/text_embedding/transformers) 

Work In Progress though
